const horticultureData = [
    // หน้า 1
    { name: 'ทุเรียน (ปลูกใหม่ 1-3 เดือน)', plantSpacing: 8, rowSpacing: 8, waterNeed: 7, flowLitersPerMinute: 1.25 },
    { name: 'ทุเรียน (เล็ก 4-12 เดือน)', plantSpacing: 8, rowSpacing: 8, waterNeed: 20, flowLitersPerMinute: 1.75 },
    { name: 'ทุเรียน (รุ่น 1-2 ปี)', plantSpacing: 8, rowSpacing: 8, waterNeed: 40, flowLitersPerMinute: 2.75 },
    { name: 'ทุเรียน (รุ่น 3-4 ปี เตรียมทำดอก)', plantSpacing: 8, rowSpacing: 8, waterNeed: 75, flowLitersPerMinute: 3.5 },
    { name: 'ทุเรียน (5-7 ปี ให้ผลผลิต)', plantSpacing: 9, rowSpacing: 9, waterNeed: 170, flowLitersPerMinute: 5 },
    { name: 'ทุเรียน (ใหญ่ 8 ปี+ ช่วงฟื้นต้น)', plantSpacing: 10, rowSpacing: 10, waterNeed: 220, flowLitersPerMinute: 6 },
    { name: 'ทุเรียน (ใหญ่ 8 ปี+ ช่วงเลี้ยงลูก)', plantSpacing: 10, rowSpacing: 10, waterNeed: 300, flowLitersPerMinute: 7 },
    { name: 'มังคุด (เล็ก 1-2 ปี)', plantSpacing: 8, rowSpacing: 8, waterNeed: 15, flowLitersPerMinute: 1.75 },
    { name: 'มังคุด (รุ่น 3-5 ปี)', plantSpacing: 8, rowSpacing: 8, waterNeed: 40, flowLitersPerMinute: 2.75 },
    { name: 'มังคุด (ให้ผลผลิต 6-10 ปี)', plantSpacing: 8, rowSpacing: 8, waterNeed: 100, flowLitersPerMinute: 4.25 },
    { name: 'มังคุด (ต้นใหญ่ 15 ปี+)', plantSpacing: 9, rowSpacing: 9, waterNeed: 175, flowLitersPerMinute: 5.5 },
    { name: 'เงาะ (เล็ก 1-2 ปี)', plantSpacing: 8, rowSpacing: 8, waterNeed: 20, flowLitersPerMinute: 2 },
    { name: 'เงาะ (รุ่น 3 ปี)', plantSpacing: 8, rowSpacing: 8, waterNeed: 50, flowLitersPerMinute: 3 },
    { name: 'เงาะ (ให้ผลผลิต 4 ปี+)', plantSpacing: 8, rowSpacing: 8, waterNeed: 125, flowLitersPerMinute: 4.5 },
    { name: 'เงาะ (ต้นใหญ่ทรงพุ่มกว้าง)', plantSpacing: 9, rowSpacing: 9, waterNeed: 200, flowLitersPerMinute: 5.5 },
    { name: 'ลำไย (เล็ก 1-2 ปี)', plantSpacing: 8, rowSpacing: 8, waterNeed: 15, flowLitersPerMinute: 1.75 },
    { name: 'ลำไย (รุ่น 3 ปี)', plantSpacing: 8, rowSpacing: 8, waterNeed: 40, flowLitersPerMinute: 2.75 },
    { name: 'ลำไย (ให้ผลผลิต 4 ปี+)', plantSpacing: 8, rowSpacing: 8, waterNeed: 115, flowLitersPerMinute: 4.5 },
    { name: 'ลำไย (ราดสาร/เร่งดอก)', plantSpacing: 8, rowSpacing: 8, waterNeed: 175, flowLitersPerMinute: 5.5 },
    { name: 'มะม่วง (เล็ก 1 ปี)', plantSpacing: 4, rowSpacing: 4, waterNeed: 10, flowLitersPerMinute: 1.25 },
    { name: 'มะม่วง (รุ่น 2-3 ปี)', plantSpacing: 6, rowSpacing: 6, waterNeed: 30, flowLitersPerMinute: 2.5 },
    { name: 'มะม่วง (ให้ผลผลิต 4 ปี+)', plantSpacing: 6, rowSpacing: 6, waterNeed: 100, flowLitersPerMinute: 4.2 },
    { name: 'มะม่วง (ทรงพุ่มใหญ่/เก็บผล)', plantSpacing: 8, rowSpacing: 8, waterNeed: 150, flowLitersPerMinute: 5 },
    { name: 'มะนาว (ลงบ่อ/ลงดิน 1-6 เดือน)', plantSpacing: 3, rowSpacing: 4, waterNeed: 7, flowLitersPerMinute: 1 },
    { name: 'มะนาว (ให้ผลผลิต 1 ปี+)', plantSpacing: 4, rowSpacing: 4, waterNeed: 40, flowLitersPerMinute: 2.5 },
    { name: 'ส้มเขียวหวาน (เล็ก 1-2 ปี)', plantSpacing: 4, rowSpacing: 4, waterNeed: 15, flowLitersPerMinute: 1.75 },
    { name: 'ส้มเขียวหวาน (ให้ผลผลิต)', plantSpacing: 5, rowSpacing: 5, waterNeed: 80, flowLitersPerMinute: 3.5 },
    { name: 'ส้มโอ (เล็ก 1-2 ปี)', plantSpacing: 6, rowSpacing: 6, waterNeed: 20, flowLitersPerMinute: 2 },
    { name: 'ส้มโอ (รุ่น 3-4 ปี)', plantSpacing: 8, rowSpacing: 8, waterNeed: 65, flowLitersPerMinute: 3.5 },
    { name: 'ส้มโอ (ให้ผลผลิตเต็มที่)', plantSpacing: 8, rowSpacing: 8, waterNeed: 150, flowLitersPerMinute: 5.5 },
    { name: 'ปาล์มน้ำมัน (เล็ก 1-2 ปี)', plantSpacing: 9, rowSpacing: 9, waterNeed: 15, flowLitersPerMinute: 1.75 },
    { name: 'ปาล์มน้ำมัน (3-5 ปี)', plantSpacing: 9, rowSpacing: 9, waterNeed: 65, flowLitersPerMinute: 3.5 },
    { name: 'ปาล์มน้ำมัน (ให้ผลผลิตเต็มที่)', plantSpacing: 9, rowSpacing: 9, waterNeed: 200, flowLitersPerMinute: 6 },
    { name: 'ยางพารา (เล็ก 1-2 ปี)', plantSpacing: 3, rowSpacing: 7, waterNeed: 10, flowLitersPerMinute: 1.25 },
    { name: 'ยางพารา (ก่อนเปิดกรีด)', plantSpacing: 3, rowSpacing: 7, waterNeed: 40, flowLitersPerMinute: 2.5 },
    { name: 'ยางพารา (ช่วงกรีด)', plantSpacing: 3, rowSpacing: 7, waterNeed: 100, flowLitersPerMinute: 3.5 },
    { name: 'มะพร้าวน้ำหอม (เล็ก 1 ปี)', plantSpacing: 6, rowSpacing: 6, waterNeed: 20, flowLitersPerMinute: 2 },
    { name: 'มะพร้าวน้ำหอม (2-3 ปี เริ่มจั่น)', plantSpacing: 6, rowSpacing: 6, waterNeed: 65, flowLitersPerMinute: 3.5 },
    { name: 'มะพร้าวน้ำหอม (ให้ผลผลิต)', plantSpacing: 6, rowSpacing: 6, waterNeed: 140, flowLitersPerMinute: 5.5 },
    { name: 'มะพร้าวแกง (ใหญ่)', plantSpacing: 8, rowSpacing: 8, waterNeed: 175, flowLitersPerMinute: 5.5 },
    { name: 'กล้วยหอม/น้ำว้า (ปลูกใหม่)', plantSpacing: 3, rowSpacing: 3, waterNeed: 7, flowLitersPerMinute: 1 },
    { name: 'กล้วยหอม/น้ำว้า (ตกเครือ)', plantSpacing: 3, rowSpacing: 3, waterNeed: 40, flowLitersPerMinute: 2.5 },
    { name: 'อะโวคาโด (เล็ก 1 ปี)', plantSpacing: 6, rowSpacing: 6, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'อะโวคาโด (2-3 ปี)', plantSpacing: 8, rowSpacing: 8, waterNeed: 40, flowLitersPerMinute: 2.75 },
    { name: 'อะโวคาโด (ให้ผลผลิต)', plantSpacing: 8, rowSpacing: 8, waterNeed: 125, flowLitersPerMinute: 4.5 },
    { name: 'โกโก้ (เล็ก 1 ปี)', plantSpacing: 3, rowSpacing: 3, waterNeed: 7, flowLitersPerMinute: 1 },
    { name: 'โกโก้ (ให้ผลผลิต)', plantSpacing: 3, rowSpacing: 3, waterNeed: 40, flowLitersPerMinute: 2.5 },
    { name: 'กาแฟโรบัสต้า/อาราบิก้า (เล็ก)', plantSpacing: 3, rowSpacing: 3, waterNeed: 7, flowLitersPerMinute: 1 },
    { name: 'กาแฟ (ให้ผลผลิต)', plantSpacing: 3, rowSpacing: 3, waterNeed: 30, flowLitersPerMinute: 2 },
    { name: 'อินทผลัม (เล็ก 1-2 ปี)', plantSpacing: 8, rowSpacing: 8, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'อินทผลัม (ให้ผลผลิต/จั่น)', plantSpacing: 8, rowSpacing: 8, waterNeed: 200, flowLitersPerMinute: 6 },
    { name: 'ไผ่กิมซุง/ไผ่เลี้ยง (หน่อไม้)', plantSpacing: 4, rowSpacing: 4, waterNeed: 40, flowLitersPerMinute: 2.5 },
    { name: 'ไผ่ (ช่วงเร่งหน่อหน้าแล้ง)', plantSpacing: 4, rowSpacing: 4, waterNeed: 65, flowLitersPerMinute: 3.5 },
    { name: 'ฝรั่งกิมจู (เล็ก 6 เดือน)', plantSpacing: 3, rowSpacing: 3, waterNeed: 7, flowLitersPerMinute: 1 },
    { name: 'ฝรั่งกิมจู (ห่อผล/เก็บผล)', plantSpacing: 3, rowSpacing: 3, waterNeed: 30, flowLitersPerMinute: 2.25 },
    { name: 'ชมพู่ทับทิมจันทร์ (เล็ก)', plantSpacing: 6, rowSpacing: 6, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'ชมพู่ทับทิมจันทร์ (ให้ผล)', plantSpacing: 6, rowSpacing: 6, waterNeed: 100, flowLitersPerMinute: 4.5 },
    { name: 'ขนุน (เล็ก)', plantSpacing: 6, rowSpacing: 6, waterNeed: 12, flowLitersPerMinute: 1.5 },
    // หน้า 2
    { name: 'ขนุน (ให้ผลผลิต)', plantSpacing: 8, rowSpacing: 8, waterNeed: 100, flowLitersPerMinute: 4.5 },
    { name: 'มะขามหวาน/เปรี้ยว (เล็ก)', plantSpacing: 8, rowSpacing: 8, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'มะขาม (ให้ฝัก)', plantSpacing: 10, rowSpacing: 10, waterNeed: 80, flowLitersPerMinute: 3.5 },
    { name: 'พุทรานมสด/พุทราจีน (เล็ก)', plantSpacing: 4, rowSpacing: 4, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'พุทรา (ให้ผลผลิต)', plantSpacing: 5, rowSpacing: 5, waterNeed: 50, flowLitersPerMinute: 2.75 },
    { name: 'น้อยหน่า/เพชรปากช่อง (เล็ก)', plantSpacing: 3, rowSpacing: 3, waterNeed: 7, flowLitersPerMinute: 1 },
    { name: 'น้อยหน่า (ให้ผลผลิต)', plantSpacing: 4, rowSpacing: 4, waterNeed: 40, flowLitersPerMinute: 2.5 },
    { name: 'ละมุด (เล็ก)', plantSpacing: 6, rowSpacing: 6, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'ละมุด (ให้ผลผลิต)', plantSpacing: 6, rowSpacing: 6, waterNeed: 65, flowLitersPerMinute: 3.5 },
    { name: 'มะยงชิด (เล็ก 1-2 ปี)', plantSpacing: 6, rowSpacing: 6, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'มะยงชิด (ให้ผลผลิต)', plantSpacing: 8, rowSpacing: 8, waterNeed: 100, flowLitersPerMinute: 4.5 },
    { name: 'กระท้อน (เล็ก)', plantSpacing: 8, rowSpacing: 8, waterNeed: 15, flowLitersPerMinute: 2 },
    { name: 'กระท้อน (ห่อผล)', plantSpacing: 10, rowSpacing: 10, waterNeed: 150, flowLitersPerMinute: 5.5 },
    { name: 'ลางสาด/ลองกอง (เล็ก)', plantSpacing: 6, rowSpacing: 6, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'ลางสาด/ลองกอง (ให้ผลผลิต)', plantSpacing: 6, rowSpacing: 6, waterNeed: 75, flowLitersPerMinute: 3.5 },
    { name: 'ลิ้นจี่ (เล็ก)', plantSpacing: 8, rowSpacing: 8, waterNeed: 15, flowLitersPerMinute: 2 },
    { name: 'ลิ้นจี่ (ให้ผลผลิต)', plantSpacing: 8, rowSpacing: 8, waterNeed: 125, flowLitersPerMinute: 4.5 },
    { name: 'สะตอ (เล็ก)', plantSpacing: 10, rowSpacing: 10, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'สะตอ (ให้ฝัก)', plantSpacing: 10, rowSpacing: 10, waterNeed: 100, flowLitersPerMinute: 4.5 },
    { name: 'มะกรูด (ตัดใบ/ขายลูก - เล็ก)', plantSpacing: 4, rowSpacing: 4, waterNeed: 6, flowLitersPerMinute: 1 },
    { name: 'มะกรูด (พุ่มใหญ่)', plantSpacing: 4, rowSpacing: 4, waterNeed: 30, flowLitersPerMinute: 2.25 },
    { name: 'หมาก (เล็ก)', plantSpacing: 3, rowSpacing: 3, waterNeed: 7, flowLitersPerMinute: 1 },
    { name: 'หมาก (ให้ผล)', plantSpacing: 3, rowSpacing: 3, waterNeed: 40, flowLitersPerMinute: 2.5 },
    { name: 'ขี้เหล็ก (เล็ก)', plantSpacing: 4, rowSpacing: 4, waterNeed: 7, flowLitersPerMinute: 1 },
    { name: 'ขี้เหล็ก (เก็บยอด)', plantSpacing: 4, rowSpacing: 4, waterNeed: 30, flowLitersPerMinute: 2.5 },
    { name: 'มะรุม (เล็ก)', plantSpacing: 3, rowSpacing: 3, waterNeed: 7, flowLitersPerMinute: 1 },
    { name: 'มะรุม (เก็บฝัก)', plantSpacing: 3, rowSpacing: 3, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'สะเดา (เล็ก)', plantSpacing: 4, rowSpacing: 4, waterNeed: 5, flowLitersPerMinute: 1 },
    { name: 'สะเดา (เก็บยอด)', plantSpacing: 4, rowSpacing: 4, waterNeed: 30, flowLitersPerMinute: 2 },
    { name: 'ผักหวานป่า (เล็ก/พี่เลี้ยง)', plantSpacing: 2, rowSpacing: 2, waterNeed: 4, flowLitersPerMinute: 0.75 },
    { name: 'ผักหวานป่า (เก็บยอด)', plantSpacing: 2, rowSpacing: 2, waterNeed: 10, flowLitersPerMinute: 1.5 },
    { name: 'แคนา (ไม้ประดับ/กินดอก เล็ก)', plantSpacing: 6, rowSpacing: 6, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'แคนา (ใหญ่)', plantSpacing: 6, rowSpacing: 6, waterNeed: 65, flowLitersPerMinute: 3.5 },
    { name: 'เสาวรส (ขึ้นค้าง - ปลูกใหม่)', plantSpacing: 3, rowSpacing: 3, waterNeed: 6, flowLitersPerMinute: 1 },
    { name: 'เสาวรส (ให้ผล)', plantSpacing: 3, rowSpacing: 3, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'องุ่น (ปลูกใหม่)', plantSpacing: 3, rowSpacing: 4, waterNeed: 5, flowLitersPerMinute: 1 },
    { name: 'องุ่น (ติดผล)', plantSpacing: 3, rowSpacing: 4, waterNeed: 30, flowLitersPerMinute: 2.5 },
    { name: 'หม่อน/มัลเบอร์รี่ (เล็ก)', plantSpacing: 3, rowSpacing: 3, waterNeed: 5, flowLitersPerMinute: 1 },
    { name: 'หม่อน/มัลเบอร์รี่ (ตัดแต่งกิ่ง/เร่งผล)', plantSpacing: 3, rowSpacing: 3, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'พุทราจีน (ใหญ่/ทำสาว)', plantSpacing: 5, rowSpacing: 5, waterNeed: 60, flowLitersPerMinute: 3 },
    { name: 'สักทอง (ปลูกใหม่ 1 ปี)', plantSpacing: 4, rowSpacing: 4, waterNeed: 7, flowLitersPerMinute: 1.25 },
    { name: 'สักทอง (3-5 ปี)', plantSpacing: 4, rowSpacing: 4, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'พะยูง (ปลูกใหม่ 1 ปี)', plantSpacing: 4, rowSpacing: 4, waterNeed: 7, flowLitersPerMinute: 1.25 },
    { name: 'พะยูง (เริ่มโต 3 ปี+)', plantSpacing: 4, rowSpacing: 4, waterNeed: 30, flowLitersPerMinute: 2.25 },
    { name: 'ยางนา (ปลูกใหม่)', plantSpacing: 4, rowSpacing: 4, waterNeed: 12, flowLitersPerMinute: 1.75 },
    { name: 'ยางนา (3 ปี+ สูงท่วมหัว)', plantSpacing: 4, rowSpacing: 6, waterNeed: 50, flowLitersPerMinute: 3 },
    { name: 'มะค่าโมง (เล็ก)', plantSpacing: 8, rowSpacing: 8, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'มะค่าโมง (ใหญ่)', plantSpacing: 8, rowSpacing: 8, waterNeed: 65, flowLitersPerMinute: 3.5 },
    { name: 'ตะเคียนทอง (เล็ก)', plantSpacing: 4, rowSpacing: 4, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'ประดู่ป่า (เล็ก)', plantSpacing: 4, rowSpacing: 4, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'ไม้กฤษณา (ปลูกใหม่)', plantSpacing: 3, rowSpacing: 3, waterNeed: 7, flowLitersPerMinute: 1 },
    { name: 'ไม้กฤษณา (ช่วงกระตุ้นสาร)', plantSpacing: 3, rowSpacing: 3, waterNeed: 40, flowLitersPerMinute: 2.5 },
    { name: 'ยูคาลิปตัส (กระดาษ/เชื้อเพลิง)', plantSpacing: 2, rowSpacing: 3, waterNeed: 7, flowLitersPerMinute: 1 },
    { name: 'ชมพูพันธุ์ทิพย์ (ไม้ประดับถนน)', plantSpacing: 6, rowSpacing: 6, waterNeed: 20, flowLitersPerMinute: 2 },
    { name: 'ราชพฤกษ์/คูน (เล็ก)', plantSpacing: 5, rowSpacing: 5, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'ราชพฤกษ์ (ใหญ่/ออกดอก)', plantSpacing: 5, rowSpacing: 5, waterNeed: 50, flowLitersPerMinute: 3 },
    { name: 'รวงผึ้ง (ไม้ประจำรัชกาลที่ 10)', plantSpacing: 6, rowSpacing: 6, waterNeed: 15, flowLitersPerMinute: 2 },
    { name: 'เหลืองปรีดียาธร', plantSpacing: 4, rowSpacing: 4, waterNeed: 15, flowLitersPerMinute: 2 },
    { name: 'อินทนิล (ใหญ่)', plantSpacing: 6, rowSpacing: 6, waterNeed: 60, flowLitersPerMinute: 3.5 },
    // หน้า 3
    { name: 'แคบ้าน/แคนา (เก็บดอก)', plantSpacing: 3, rowSpacing: 3, waterNeed: 20, flowLitersPerMinute: 2 },
    { name: 'มะรุม (กินฝัก/ใบ)', plantSpacing: 3, rowSpacing: 3, waterNeed: 20, flowLitersPerMinute: 2 },
    { name: 'สะเดาทวาย (ขมน้อย)', plantSpacing: 4, rowSpacing: 4, waterNeed: 20, flowLitersPerMinute: 2 },
    { name: 'เพกาเตี้ย (ลิ้นฟ้า)', plantSpacing: 3, rowSpacing: 3, waterNeed: 15, flowLitersPerMinute: 2 },
    { name: 'ระกำ (เปรี้ยว/หวาน)', plantSpacing: 3, rowSpacing: 3, waterNeed: 25, flowLitersPerMinute: 2.5 },
    { name: 'มะไฟ (หวาน/เปรี้ยว)', plantSpacing: 6, rowSpacing: 6, waterNeed: 40, flowLitersPerMinute: 2.75 },
    { name: 'ตะลิงปลิง (เล็ก)', plantSpacing: 4, rowSpacing: 4, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'ตะลิงปลิง (ให้ผล)', plantSpacing: 4, rowSpacing: 4, waterNeed: 50, flowLitersPerMinute: 3 },
    { name: 'มะยม (ชิด/ประดับ)', plantSpacing: 3, rowSpacing: 3, waterNeed: 20, flowLitersPerMinute: 2 },
    { name: 'มะขามป้อม (ยักษ์อินเดีย)', plantSpacing: 6, rowSpacing: 6, waterNeed: 25, flowLitersPerMinute: 2.25 },
    { name: 'มะกอกน้ำ (ดอง)', plantSpacing: 6, rowSpacing: 6, waterNeed: 40, flowLitersPerMinute: 2.75 },
    { name: 'มะกอกฝรั่ง (กินสด)', plantSpacing: 4, rowSpacing: 4, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'มะตูม (ทำชา)', plantSpacing: 6, rowSpacing: 6, waterNeed: 30, flowLitersPerMinute: 2.5 },
    { name: 'มะขวิด', plantSpacing: 6, rowSpacing: 6, waterNeed: 30, flowLitersPerMinute: 2.5 },
    { name: 'ลูกหว้า (ยักษ์)', plantSpacing: 6, rowSpacing: 6, waterNeed: 40, flowLitersPerMinute: 3 },
    { name: 'ชมพู่มะเหมี่ยว (โบราณ)', plantSpacing: 8, rowSpacing: 8, waterNeed: 65, flowLitersPerMinute: 3.5 },
    { name: 'สาเก (พันธุ์ข้าวเหนียว)', plantSpacing: 8, rowSpacing: 8, waterNeed: 75, flowLitersPerMinute: 4.5 },
    { name: 'จำปาดะ (ภาคใต้)', plantSpacing: 8, rowSpacing: 8, waterNeed: 65, flowLitersPerMinute: 3.5 },
    { name: 'ฟักข้าว (ขึ้นค้าง)', plantSpacing: 3, rowSpacing: 3, waterNeed: 15, flowLitersPerMinute: 2 },
    { name: 'องุ่นบราซิล (Jabuticaba)', plantSpacing: 4, rowSpacing: 4, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'มะม่วงหาวมะนาวโห่', plantSpacing: 3, rowSpacing: 3, waterNeed: 15, flowLitersPerMinute: 1.75 },
    { name: 'ทุเรียนก้านยาว (เล็ก)', plantSpacing: 10, rowSpacing: 10, waterNeed: 20, flowLitersPerMinute: 2 },
    { name: 'ทุเรียนก้านยาว (ให้ผล)', plantSpacing: 10, rowSpacing: 10, waterNeed: 250, flowLitersPerMinute: 7 },
    { name: 'ทุเรียนพวงมณี (เล็ก)', plantSpacing: 8, rowSpacing: 8, waterNeed: 15, flowLitersPerMinute: 1.75 },
    { name: 'ทุเรียนพวงมณี (ให้ผล)', plantSpacing: 8, rowSpacing: 8, waterNeed: 175, flowLitersPerMinute: 4.5 },
    { name: 'ทุเรียนมูซานคิง (เล็ก)', plantSpacing: 9, rowSpacing: 9, waterNeed: 20, flowLitersPerMinute: 2 },
    { name: 'ทุเรียนหนามดำ (Ochee)', plantSpacing: 9, rowSpacing: 9, waterNeed: 20, flowLitersPerMinute: 2 },
    { name: 'มะม่วงน้ำดอกไม้สีทอง (ทำนอกฤดู)', plantSpacing: 4, rowSpacing: 4, waterNeed: 80, flowLitersPerMinute: 3.5 },
    { name: 'มะม่วงมหาชนก', plantSpacing: 6, rowSpacing: 6, waterNeed: 70, flowLitersPerMinute: 3.5 },
    { name: 'มะม่วงเขียวเสวย', plantSpacing: 6, rowSpacing: 6, waterNeed: 90, flowLitersPerMinute: 3.5 },
    { name: 'มะม่วง R2E2 (ลูกใหญ่)', plantSpacing: 6, rowSpacing: 6, waterNeed: 100, flowLitersPerMinute: 4.5 },
    { name: 'มะม่วงเบา (สงขลา)', plantSpacing: 6, rowSpacing: 6, waterNeed: 50, flowLitersPerMinute: 2.75 },
    { name: 'ส้มโอทับทิมสยาม (เล็ก)', plantSpacing: 6, rowSpacing: 6, waterNeed: 20, flowLitersPerMinute: 2 },
    { name: 'ส้มโอทับทิมสยาม (ให้ผล)', plantSpacing: 6, rowSpacing: 6, waterNeed: 90, flowLitersPerMinute: 4.5 },
    { name: 'มะนาวแป้นพิจิตร (ทนโรค)', plantSpacing: 3, rowSpacing: 4, waterNeed: 40, flowLitersPerMinute: 2.5 },
    { name: 'มะนาวไร้เมล็ด (ตาฮิติ)', plantSpacing: 3, rowSpacing: 4, waterNeed: 40, flowLitersPerMinute: 2.5 },
    { name: 'จำปี (เก็บดอก)', plantSpacing: 4, rowSpacing: 4, waterNeed: 40, flowLitersPerMinute: 2.75 },
    { name: 'จำปา', plantSpacing: 4, rowSpacing: 4, waterNeed: 40, flowLitersPerMinute: 2.75 },
    { name: 'กระดังงาสงขลา', plantSpacing: 4, rowSpacing: 4, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'พิกุล (ไม้ขุดล้อม/ประดับ)', plantSpacing: 5, rowSpacing: 5, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'บุนนาค', plantSpacing: 5, rowSpacing: 5, waterNeed: 30, flowLitersPerMinute: 2 },
    { name: 'สารภี', plantSpacing: 5, rowSpacing: 5, waterNeed: 30, flowLitersPerMinute: 2 },
    { name: 'มะคาเดเมีย (ดอย/ที่สูง)', plantSpacing: 8, rowSpacing: 8, waterNeed: 50, flowLitersPerMinute: 3 },
    { name: 'มะม่วงหิมพานต์ (เล็ก)', plantSpacing: 6, rowSpacing: 6, waterNeed: 10, flowLitersPerMinute: 1.5 },
    { name: 'มะม่วงหิมพานต์ (ให้ผล)', plantSpacing: 6, rowSpacing: 6, waterNeed: 65, flowLitersPerMinute: 3.5 },
    { name: 'ไผ่ซางหม่น (ลำตรง/เฟอร์นิเจอร์)', plantSpacing: 4, rowSpacing: 4, waterNeed: 40, flowLitersPerMinute: 2.75 },
    { name: 'ปาล์มหางกระรอก (ประดับ)', plantSpacing: 3, rowSpacing: 3, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'กระท่อม (ก้านแดง/แตงกวา - เล็ก)', plantSpacing: 4, rowSpacing: 4, waterNeed: 7, flowLitersPerMinute: 1.25 },
    { name: 'กระท่อม (ทรงพุ่มใหญ่ - เก็บใบ)', plantSpacing: 4, rowSpacing: 4, waterNeed: 50, flowLitersPerMinute: 3.5 },
    { name: 'มะขามเทศ (เพชรโนนไทย - เล็ก)', plantSpacing: 8, rowSpacing: 8, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'มะขามเทศ (ให้ฝัก - ต้องการน้ำเลี้ยงฝัก)', plantSpacing: 10, rowSpacing: 10, waterNeed: 100, flowLitersPerMinute: 4.5 },
    { name: 'ฟิกส์/มะเดื่อฝรั่ง (ลงดิน - ต้นใหญ่)', plantSpacing: 3, rowSpacing: 3, waterNeed: 20, flowLitersPerMinute: 1.75 },
    { name: 'ทับทิม (พันธุ์จรัสแสง/อินเดีย - เล็ก)', plantSpacing: 4, rowSpacing: 4, waterNeed: 5, flowLitersPerMinute: 1 },
    { name: 'ทับทิม (ให้ผลผลิต)', plantSpacing: 4, rowSpacing: 4, waterNeed: 35, flowLitersPerMinute: 2.25 },
    { name: 'อินทผลัม (เพาะเนื้อเยื่อ - กินผลสด)', plantSpacing: 8, rowSpacing: 8, waterNeed: 200, flowLitersPerMinute: 6 },
    { name: 'พลับ (Persimmon - เล็ก)', plantSpacing: 6, rowSpacing: 6, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'พลับ (ให้ผลผลิต)', plantSpacing: 6, rowSpacing: 6, waterNeed: 65, flowLitersPerMinute: 3.5 },
    { name: 'พืช/ท้อ (Peach - เล็ก)', plantSpacing: 6, rowSpacing: 6, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'พืช/ท้อ (ติดผล)', plantSpacing: 6, rowSpacing: 6, waterNeed: 50, flowLitersPerMinute: 3 },
    // หน้า 4
    { name: 'บ๊วย (Plum)', plantSpacing: 6, rowSpacing: 6, waterNeed: 50, flowLitersPerMinute: 3 },
    { name: 'สาลี่ (Pear - บนดอย)', plantSpacing: 6, rowSpacing: 6, waterNeed: 60, flowLitersPerMinute: 3 },
    { name: 'เชอร์รี่ดอย (นางพญาเสือโคร่ง)', plantSpacing: 6, rowSpacing: 6, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'ลูกเนียง (พืชตระกูลถั่ว - ยืนต้น)', plantSpacing: 8, rowSpacing: 8, waterNeed: 15, flowLitersPerMinute: 1.75 },
    { name: 'ลูกเนียง (ติดฝัก/ลูก)', plantSpacing: 8, rowSpacing: 8, waterNeed: 80, flowLitersPerMinute: 4.5 },
    { name: 'ลูกเหรียง (ไม้ป่ากินเมล็ด)', plantSpacing: 8, rowSpacing: 8, waterNeed: 65, flowLitersPerMinute: 3.5 },
    { name: 'สะตอข้าว (พันธุ์เบา)', plantSpacing: 8, rowSpacing: 8, waterNeed: 65, flowLitersPerMinute: 3.5 },
    { name: 'ติ้ว (ติ้วขาว/ติ้วขน - กินยอด)', plantSpacing: 4, rowSpacing: 4, waterNeed: 15, flowLitersPerMinute: 2 },
    { name: 'กระโดน (กินยอดอ่อน)', plantSpacing: 5, rowSpacing: 5, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'เม็ก (เสม็ดขาว - กินยอด)', plantSpacing: 4, rowSpacing: 4, waterNeed: 15, flowLitersPerMinute: 1.75 },
    { name: 'มันปู (ผักเหนาะภาคใต้)', plantSpacing: 3, rowSpacing: 3, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'ลีลาวดี (Plumeria - ขุดล้อม)', plantSpacing: 4, rowSpacing: 4, waterNeed: 20, flowLitersPerMinute: 2 },
    { name: 'หางนกยูงฝรั่ง (ร่มเงา)', plantSpacing: 8, rowSpacing: 8, waterNeed: 50, flowLitersPerMinute: 3 },
    { name: 'กัลปพฤกษ์ (นางพญาเสือโคร่งอีสาน)', plantSpacing: 6, rowSpacing: 6, waterNeed: 40, flowLitersPerMinute: 2.75 },
    { name: 'ชงโค (เสี้ยว - ดอกม่วง)', plantSpacing: 5, rowSpacing: 5, waterNeed: 30, flowLitersPerMinute: 2.25 },
    { name: 'ทองกวาว (ดอกส้ม - ทนแล้ง)', plantSpacing: 6, rowSpacing: 6, waterNeed: 20, flowLitersPerMinute: 2 },
    { name: 'ศรีตรัง (ดอกม่วง)', plantSpacing: 6, rowSpacing: 6, waterNeed: 40, flowLitersPerMinute: 2.75 },
    { name: 'ปีบ (กาสะลอง - ดอกหอม)', plantSpacing: 5, rowSpacing: 5, waterNeed: 35, flowLitersPerMinute: 2.5 },
    { name: 'ตะแบก/เสลา (ไม้ถนน)', plantSpacing: 6, rowSpacing: 6, waterNeed: 40, flowLitersPerMinute: 3 },
    { name: 'ชัยพฤกษ์', plantSpacing: 6, rowSpacing: 6, waterNeed: 40, flowLitersPerMinute: 3 },
    { name: 'จิกน้ำ/จิกเศรษฐี (ชอบน้ำ)', plantSpacing: 5, rowSpacing: 5, waterNeed: 50, flowLitersPerMinute: 3 },
    { name: 'ประยงค์ (ดอกหอม)', plantSpacing: 3, rowSpacing: 3, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'หอมหมื่นลี้ (ไม้เมืองหนาว/หอม)', plantSpacing: 3, rowSpacing: 3, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'ไม้แดง (Xylia - โตช้า)', plantSpacing: 4, rowSpacing: 4, waterNeed: 15, flowLitersPerMinute: 1.75 },
    { name: 'ไม้เต็ง (ทนแล้งจัด)', plantSpacing: 4, rowSpacing: 4, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'ไม้รัง (ทนแล้งจัด)', plantSpacing: 4, rowSpacing: 4, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'พะยอม (ไม้ดอกหอม/เนื้อแข็ง)', plantSpacing: 6, rowSpacing: 6, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'กันเกรา (ไม้มงคล)', plantSpacing: 5, rowSpacing: 5, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'ตะเคียนหิน (Hopea ferrea)', plantSpacing: 4, rowSpacing: 4, waterNeed: 20, flowLitersPerMinute: 2 },
    { name: 'ชิงชัน (ไม้แพงระดับพะยูง)', plantSpacing: 4, rowSpacing: 4, waterNeed: 20, flowLitersPerMinute: 2 },
    { name: 'มะฮอกกานี (ใบใหญ่)', plantSpacing: 6, rowSpacing: 6, waterNeed: 35, flowLitersPerMinute: 2.75 },
    { name: 'สนสามใบ (ปลูกพื้นที่สูง)', plantSpacing: 4, rowSpacing: 4, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'อบเชย (Cinnamon - เก็บเปลือก)', plantSpacing: 4, rowSpacing: 4, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'กานพลู (Clove - ชอบชื้น)', plantSpacing: 4, rowSpacing: 4, waterNeed: 30, flowLitersPerMinute: 2.25 },
    { name: 'จันทน์เทศ (Nutmeg)', plantSpacing: 6, rowSpacing: 6, waterNeed: 40, flowLitersPerMinute: 3 },
    { name: 'มะหาด (กินผล/ทำยา)', plantSpacing: 8, rowSpacing: 8, waterNeed: 50, flowLitersPerMinute: 3 },
    { name: 'ลูกหยี (ภาคใต้)', plantSpacing: 8, rowSpacing: 8, waterNeed: 65, flowLitersPerMinute: 3.5 },
    { name: 'สตาร์แอปเปิ้ล (ลูกน้ำนม)', plantSpacing: 6, rowSpacing: 6, waterNeed: 40, flowLitersPerMinute: 2.75 },
    { name: 'เซียนท้อ (ละมุดเขมร/ม่อนไข่)', plantSpacing: 5, rowSpacing: 5, waterNeed: 30, flowLitersPerMinute: 2.25 },
    { name: 'น้อยโหน่ง (Bullock\'s Heart)', plantSpacing: 5, rowSpacing: 5, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'มะขวิด (โบราณ)', plantSpacing: 6, rowSpacing: 6, waterNeed: 40, flowLitersPerMinute: 3 },
    { name: 'ตะขบยักษ์ (ไร้หนาม - ผลไม้เด็ก)', plantSpacing: 4, rowSpacing: 4, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'มะเฟือง (หวาน/เปรี้ยว)', plantSpacing: 5, rowSpacing: 5, waterNeed: 40, flowLitersPerMinute: 3 },
    { name: 'มะดัน (เปรี้ยว/ดอง)', plantSpacing: 5, rowSpacing: 5, waterNeed: 40, flowLitersPerMinute: 3 },
    { name: 'สมอไทย (ยาอายุวัฒนะ)', plantSpacing: 8, rowSpacing: 8, waterNeed: 50, flowLitersPerMinute: 3 },
    { name: 'สมอพิเภก', plantSpacing: 8, rowSpacing: 8, waterNeed: 50, flowLitersPerMinute: 3 },
    { name: 'ชำมะเลียง (ลูกดำๆ)', plantSpacing: 4, rowSpacing: 4, waterNeed: 20, flowLitersPerMinute: 2 },
    { name: 'หว้า (ลูกหว้า)', plantSpacing: 8, rowSpacing: 8, waterNeed: 50, flowLitersPerMinute: 3 },
    { name: 'มะหลอด (ผลไม้เหนือ)', plantSpacing: 4, rowSpacing: 4, waterNeed: 15, flowLitersPerMinute: 2 },
    { name: 'ไผ่สีสุก (ลำหนา/งานโครงสร้าง)', plantSpacing: 5, rowSpacing: 5, waterNeed: 50, flowLitersPerMinute: 3 },
    { name: 'ไผ่ตงลืมแล้ง (หน่อดก)', plantSpacing: 4, rowSpacing: 4, waterNeed: 40, flowLitersPerMinute: 2.75 },
    { name: 'ไผ่หวานเพชรน้ำผึ้ง', plantSpacing: 3, rowSpacing: 3, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'สาละลังกา (ลูกใหญ่/ดอกหอม)', plantSpacing: 6, rowSpacing: 6, waterNeed: 40, flowLitersPerMinute: 3 },
    { name: 'จันทน์กะพ้อ (หอมแรง/หายาก)', plantSpacing: 5, rowSpacing: 5, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'จันอิน/จันโอ (ลูกเหลืองหอม)', plantSpacing: 6, rowSpacing: 6, waterNeed: 40, flowLitersPerMinute: 3 },
    { name: 'ทรงบาดาล (ดอกเหลือง)', plantSpacing: 4, rowSpacing: 4, waterNeed: 15, flowLitersPerMinute: 2 },
    { name: 'แก้วเจ้าจอม (ใบสวย/โตช้า)', plantSpacing: 4, rowSpacing: 4, waterNeed: 15, flowLitersPerMinute: 1.75 },
    { name: 'ไทรย้อย (Banyan - ต้นใหญ่มาก)', plantSpacing: 10, rowSpacing: 10, waterNeed: 100, flowLitersPerMinute: 5 },
    { name: 'โพธิ์ (ต้นใหญ่/วัด)', plantSpacing: 10, rowSpacing: 10, waterNeed: 100, flowLitersPerMinute: 5 },
    // หน้า 5
    { name: 'ปาล์มพัด (Fan Palm)', plantSpacing: 4, rowSpacing: 4, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'กล้วยพัด (Traveler\'s Palm)', plantSpacing: 4, rowSpacing: 4, waterNeed: 40, flowLitersPerMinute: 3 },
    { name: 'กระถินณรงค์ (โตเร็วมาก)', plantSpacing: 3, rowSpacing: 3, waterNeed: 15, flowLitersPerMinute: 1.5 },
    { name: 'มะพูด (Garcinia dulcis - ผลเหลือง)', plantSpacing: 6, rowSpacing: 6, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'ชะมวง (เก็บใบทำแกง)', plantSpacing: 4, rowSpacing: 4, waterNeed: 15, flowLitersPerMinute: 1.75 },
    { name: 'ส้มซ่า (หายาก - ผิวทำอาหาร)', plantSpacing: 4, rowSpacing: 4, waterNeed: 35, flowLitersPerMinute: 2.5 },
    { name: 'มะงั่ว (ลูกใหญ่เหมือนมะนาวยักษ์)', plantSpacing: 4, rowSpacing: 4, waterNeed: 40, flowLitersPerMinute: 3 },
    { name: 'มะกรูดหวาน (กินเนื้อได้)', plantSpacing: 4, rowSpacing: 4, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'มะสัง (ทำยอด/บอนไซ)', plantSpacing: 4, rowSpacing: 4, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'มะขามป้อม (พันธุ์ป่า - ยา)', plantSpacing: 6, rowSpacing: 6, waterNeed: 20, flowLitersPerMinute: 2 },
    { name: 'ลูกจัน (ไม้ผลโบราณกลิ่นหอม)', plantSpacing: 8, rowSpacing: 8, waterNeed: 50, flowLitersPerMinute: 3 },
    { name: 'ลูกอิน (คู่กับลูกจัน)', plantSpacing: 8, rowSpacing: 8, waterNeed: 50, flowLitersPerMinute: 3 },
    { name: 'ตะคร้อ (รสเปรี้ยว/ป่า)', plantSpacing: 8, rowSpacing: 8, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'คอแลน (ลิ้นจี่ป่า)', plantSpacing: 6, rowSpacing: 6, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'หมากเม่า (Berry Thai)', plantSpacing: 4, rowSpacing: 4, waterNeed: 15, flowLitersPerMinute: 1.75 },
    { name: 'มะเกี๋ยง (ผลไม้เหนือ)', plantSpacing: 4, rowSpacing: 4, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'เพกา (ลิ้นฟ้า - พันธุ์ฝักยาว)', plantSpacing: 3, rowSpacing: 3, waterNeed: 15, flowLitersPerMinute: 1.75 },
    { name: 'กุ่มบก (ยอดดอง)', plantSpacing: 5, rowSpacing: 5, waterNeed: 20, flowLitersPerMinute: 2 },
    { name: 'กุ่มน้ำ (ชอบริมน้ำ)', plantSpacing: 5, rowSpacing: 5, waterNeed: 30, flowLitersPerMinute: 3 },
    { name: 'ยอ (Noni - ยา/อาหาร)', plantSpacing: 3, rowSpacing: 3, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'สมอดีงู', plantSpacing: 6, rowSpacing: 6, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'มะกอกป่า (ใส่ส้มตำ)', plantSpacing: 8, rowSpacing: 8, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'กล้วยหักมุก (ปิ้ง)', plantSpacing: 3, rowSpacing: 3, waterNeed: 20, flowLitersPerMinute: 2 },
    { name: 'กล้วยน้ำว้าปากช่อง 50', plantSpacing: 4, rowSpacing: 4, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'กล้วยน้ำว้ามะลิอ่อง', plantSpacing: 3, rowSpacing: 3, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'กล้วยสาวกระทืบหอ', plantSpacing: 2, rowSpacing: 2, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'กล้วยเทพรส (ลูกใหญ่)', plantSpacing: 3, rowSpacing: 3, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'กล้วยนาก (เปลือกแดง)', plantSpacing: 3, rowSpacing: 3, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'กล้วยหิน (ยะลา - ต้ม/ฉาบ)', plantSpacing: 3, rowSpacing: 3, waterNeed: 30, flowLitersPerMinute: 2.25 },
    { name: 'กล้วยร้อยหวี (ประดับ)', plantSpacing: 3, rowSpacing: 3, waterNeed: 15, flowLitersPerMinute: 1.5 },
    { name: 'ยางเหียง (ใบใหญ่/ทนแล้งจัด)', plantSpacing: 4, rowSpacing: 4, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'ยางพลวง (ดินลูกรังปลูกได้)', plantSpacing: 4, rowSpacing: 4, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'ยางแดง', plantSpacing: 4, rowSpacing: 4, waterNeed: 15, flowLitersPerMinute: 1.5 },
    { name: 'ตะเคียนทราย', plantSpacing: 4, rowSpacing: 4, waterNeed: 15, flowLitersPerMinute: 1.5 },
    { name: 'กระบาก (ไม้ใหญ่)', plantSpacing: 6, rowSpacing: 6, waterNeed: 20, flowLitersPerMinute: 2 },
    { name: 'เคี่ยม (ไม้เนื้อแข็งภาคใต้)', plantSpacing: 4, rowSpacing: 4, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'เคี่ยมคะนอง', plantSpacing: 4, rowSpacing: 4, waterNeed: 20, flowLitersPerMinute: 2 },
    { name: 'พันจำ', plantSpacing: 5, rowSpacing: 5, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'ไข่เขียว', plantSpacing: 4, rowSpacing: 4, waterNeed: 15, flowLitersPerMinute: 1.5 },
    { name: 'นนทรี (ไม้โตเร็ว/ร่มเงา)', plantSpacing: 6, rowSpacing: 6, waterNeed: 40, flowLitersPerMinute: 3 },
    { name: 'ประดู่บ้าน (ดอกหอม)', plantSpacing: 6, rowSpacing: 6, waterNeed: 35, flowLitersPerMinute: 3 },
    { name: 'ประดู่แดง (ดอกแดงสวย)', plantSpacing: 5, rowSpacing: 5, waterNeed: 30, flowLitersPerMinute: 2.25 },
    { name: 'สะเดาเทียม (ไม้เนื้อขาว - ภาคใต้)', plantSpacing: 4, rowSpacing: 4, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'เลี่ยน (Senna - โตเร็ว)', plantSpacing: 4, rowSpacing: 4, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'สำโรง (ฝักกินได้/ไม้เบา)', plantSpacing: 5, rowSpacing: 5, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'งิ้ว (นุ่น - หมอน)', plantSpacing: 6, rowSpacing: 6, waterNeed: 15, flowLitersPerMinute: 2 },
    { name: 'ทองหลางน้ำ (กินใบ/พี่เลี้ยงทุเรียน)', plantSpacing: 4, rowSpacing: 4, waterNeed: 40, flowLitersPerMinute: 3 },
    { name: 'ทองหลางป่า', plantSpacing: 4, rowSpacing: 4, waterNeed: 20, flowLitersPerMinute: 1.5 },
    { name: 'จามจุรี (ฉำฉา - เลี้ยงครั่ง/ร่มเงา)', plantSpacing: 10, rowSpacing: 10, waterNeed: 75, flowLitersPerMinute: 4.5 },
    { name: 'ลำดวน (ดอกหอม/ขนม)', plantSpacing: 4, rowSpacing: 4, waterNeed: 15, flowLitersPerMinute: 1.5 },
    { name: 'ลำดวนแดง', plantSpacing: 4, rowSpacing: 4, waterNeed: 15, flowLitersPerMinute: 1.5 },
    { name: 'จำปาป่า', plantSpacing: 5, rowSpacing: 5, waterNeed: 30, flowLitersPerMinute: 2.25 },
    { name: 'จำปาทอง', plantSpacing: 5, rowSpacing: 5, waterNeed: 30, flowLitersPerMinute: 2.25 },
    { name: 'แก้วมุกดา (ใบใหญ่/ดอกหอม)', plantSpacing: 3, rowSpacing: 3, waterNeed: 15, flowLitersPerMinute: 1.75 },
    { name: 'บุหงาส่าหรี (พุ่ม/ดอกหอม)', plantSpacing: 3, rowSpacing: 3, waterNeed: 15, flowLitersPerMinute: 1.5 },
    { name: 'กรรณิการ์ (ดอกกลางคืน)', plantSpacing: 3, rowSpacing: 3, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'เข็มป่า (ดอกหอม)', plantSpacing: 3, rowSpacing: 3, waterNeed: 12, flowLitersPerMinute: 1.25 },
    { name: 'สุพรรณิการ์ (ฝ้ายคำ - ดอกเหลือง)', plantSpacing: 5, rowSpacing: 5, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'เหลืองอินเดีย (ดอกบานพร้อมกัน)', plantSpacing: 5, rowSpacing: 5, waterNeed: 25, flowLitersPerMinute: 2 },
    // หน้า 6
    { name: 'แคแสด (African Tulip)', plantSpacing: 6, rowSpacing: 6, waterNeed: 40, flowLitersPerMinute: 3 },
    { name: 'อินจัน (ไม้โบราณ)', plantSpacing: 6, rowSpacing: 6, waterNeed: 30, flowLitersPerMinute: 2.5 },
    { name: 'ตีนเป็ดน้ำ (ลูกกลม/ไม้ชายน้ำ)', plantSpacing: 5, rowSpacing: 5, waterNeed: 50, flowLitersPerMinute: 3 },
    { name: 'ตาลโตนด (Sugar Palm - ปลูกแนว)', plantSpacing: 6, rowSpacing: 6, waterNeed: 15, flowLitersPerMinute: 2 },
    { name: 'ปาล์มขวด (Royal Palm)', plantSpacing: 4, rowSpacing: 4, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'สนฉัตร (Norfolk Pine)', plantSpacing: 6, rowSpacing: 6, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'ยางอินเดีย (Rubber Plant)', plantSpacing: 3, rowSpacing: 3, waterNeed: 20, flowLitersPerMinute: 2 },
    { name: 'หลิวลู่ลม (ริมน้ำ)', plantSpacing: 3, rowSpacing: 3, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'รางจืด (ถอนพิษ - เถา)', plantSpacing: 3, rowSpacing: 3, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'ชุมเห็ดเทศ (ยาระบาย)', plantSpacing: 2, rowSpacing: 2, waterNeed: 7, flowLitersPerMinute: 1 },
    { name: 'อบเชยไทย (สมุนไพรเปลือก)', plantSpacing: 4, rowSpacing: 4, waterNeed: 15, flowLitersPerMinute: 2 },
    { name: 'การบูร (Camphor Tree)', plantSpacing: 5, rowSpacing: 5, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'แก้วมังกรเนื้อขาว (เวียดนาม - ปลูกใหม่)', plantSpacing: 3, rowSpacing: 3, waterNeed: 4, flowLitersPerMinute: 0.75 },
    { name: 'แก้วมังกรเนื้อแดง (ไต้หวัน/สยามเรด)', plantSpacing: 3, rowSpacing: 3, waterNeed: 4, flowLitersPerMinute: 0.75 },
    { name: 'แก้วมังกรสีเหลือง (อิสราเอล/เอกวาดอร์)', plantSpacing: 3, rowSpacing: 3, waterNeed: 4, flowLitersPerMinute: 0.75 },
    { name: 'แก้วมังกร (ช่วงเร่งดอก/ติดผล)', plantSpacing: 3, rowSpacing: 3, waterNeed: 12, flowLitersPerMinute: 1.25 },
    { name: 'ฝรั่งหงเป่าสือ (ไส้แดง - เล็ก)', plantSpacing: 4, rowSpacing: 4, waterNeed: 7, flowLitersPerMinute: 1 },
    { name: 'ฝรั่งหงเป่าสือ (ห่อผล/เก็บเกี่ยว)', plantSpacing: 3, rowSpacing: 3, waterNeed: 30, flowLitersPerMinute: 2.25 },
    { name: 'ฝรั่งเพิ่นหงมี่ (ไส้ชมพู)', plantSpacing: 3, rowSpacing: 3, waterNeed: 35, flowLitersPerMinute: 2.25 },
    { name: 'ฝรั่งแดงโม (Surinam Cherry - แปลก)', plantSpacing: 3, rowSpacing: 3, waterNeed: 20, flowLitersPerMinute: 1.5 },
    { name: 'ขนุนแดงสุริยา (เนื้อแดง)', plantSpacing: 8, rowSpacing: 8, waterNeed: 70, flowLitersPerMinute: 3.5 },
    { name: 'ขนุนทองประเสริฐ (ยอดนิยม)', plantSpacing: 8, rowSpacing: 8, waterNeed: 70, flowLitersPerMinute: 3.5 },
    { name: 'ขนุนเพชรราชา', plantSpacing: 8, rowSpacing: 8, waterNeed: 70, flowLitersPerMinute: 3.5 },
    { name: 'กาแฟลิเบอริก้า (กาแฟโบราณ/พุ่มใหญ่)', plantSpacing: 4, rowSpacing: 4, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'ทุเรียนชะนี (ทนโรครากเน่าดีกว่าหมอนทอง)', plantSpacing: 9, rowSpacing: 9, waterNeed: 175, flowLitersPerMinute: 5 },
    { name: 'ทุเรียนกระดุม (ผลดก/ออกไว)', plantSpacing: 8, rowSpacing: 8, waterNeed: 135, flowLitersPerMinute: 4.5 },
    { name: 'ทุเรียนหลงลับแล (อุตรดิตถ์)', plantSpacing: 8, rowSpacing: 8, waterNeed: 135, flowLitersPerMinute: 4.5 },
    { name: 'ทุเรียนหลินลับแล', plantSpacing: 8, rowSpacing: 8, waterNeed: 135, flowLitersPerMinute: 4.5 },
    { name: 'ทุเรียนนกหยิบ', plantSpacing: 9, rowSpacing: 9, waterNeed: 175, flowLitersPerMinute: 5 },
    { name: 'ทุเรียนกบชายน้ำ (พันธุ์โบราณ/สะเทินน้ำ)', plantSpacing: 10, rowSpacing: 10, waterNeed: 215, flowLitersPerMinute: 6 },
    { name: 'ทุเรียนพวงมณี (ลูกเล็ก/ดก)', plantSpacing: 8, rowSpacing: 8, waterNeed: 125, flowLitersPerMinute: 4.25 },
    { name: 'ทุเรียนสาลิกา (พังงา)', plantSpacing: 9, rowSpacing: 9, waterNeed: 175, flowLitersPerMinute: 5 },
    { name: 'ทุเรียนหมอนทอง (ยอดฮิต - ระยะชิด)', plantSpacing: 6, rowSpacing: 8, waterNeed: 100, flowLitersPerMinute: 3.5 },
    { name: 'ทุเรียนหมอนทอง (ระยะมาตรฐาน)', plantSpacing: 9, rowSpacing: 9, waterNeed: 200, flowLitersPerMinute: 6 },
    { name: 'มะม่วงอกร่อง (ทอง/พิกุลทอง)', plantSpacing: 8, rowSpacing: 8, waterNeed: 90, flowLitersPerMinute: 3.5 },
    { name: 'มะม่วงแก้วขมิ้น (กินดิบ/ส่งออก)', plantSpacing: 6, rowSpacing: 6, waterNeed: 70, flowLitersPerMinute: 3 },
    { name: 'มะม่วงฟ้าลั่น (กินดิบ/มัน)', plantSpacing: 6, rowSpacing: 6, waterNeed: 70, flowLitersPerMinute: 3 },
    { name: 'มะม่วงโชคอนันต์ (ออกลูกทั้งปี/ทวาย)', plantSpacing: 6, rowSpacing: 6, waterNeed: 60, flowLitersPerMinute: 2.75 },
    { name: 'มะม่วงยายกล่ำ (โบราณ/ลูกกลม)', plantSpacing: 8, rowSpacing: 8, waterNeed: 90, flowLitersPerMinute: 3.5 },
    { name: 'มะม่วงมันขุนศรี (หายาก)', plantSpacing: 8, rowSpacing: 8, waterNeed: 90, flowLitersPerMinute: 3.5 },
    { name: 'มะม่วงเขียวใหญ่ (ยักษ์)', plantSpacing: 8, rowSpacing: 8, waterNeed: 125, flowLitersPerMinute: 4.5 },
    { name: 'มะม่วงแดงจักรพรรดิ์ (ผิวแดง)', plantSpacing: 6, rowSpacing: 6, waterNeed: 75, flowLitersPerMinute: 3 },
    { name: 'มะม่วงอาร์ทูอีทู (R2E2 - ลูกแดง)', plantSpacing: 8, rowSpacing: 8, waterNeed: 100, flowLitersPerMinute: 4 },
    { name: 'มะม่วงป่า/มะม่วงกะล่อน (ตอม่อ/ทนแล้ง)', plantSpacing: 10, rowSpacing: 10, waterNeed: 75, flowLitersPerMinute: 4 },
    { name: 'มะนาวนิ้ว (Finger Lime - แฟนซี)', plantSpacing: 3, rowSpacing: 3, waterNeed: 7, flowLitersPerMinute: 1 },
    { name: 'ส้มโอมือ (Buddha\'s Hand - ยา)', plantSpacing: 3, rowSpacing: 3, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'ส้มโอขาวแตงกวา (ชัยนาท)', plantSpacing: 8, rowSpacing: 8, waterNeed: 100, flowLitersPerMinute: 4.5 },
    { name: 'ส้มโอทองดี', plantSpacing: 8, rowSpacing: 8, waterNeed: 100, flowLitersPerMinute: 4.5 },
    { name: 'มะนาวตาฮิติ (ทนโรค/ไร้เมล็ด)', plantSpacing: 4, rowSpacing: 4, waterNeed: 40, flowLitersPerMinute: 2.5 },
    { name: 'เลมอน (Lemon - พันธุ์ยูเรก้า)', plantSpacing: 4, rowSpacing: 4, waterNeed: 40, flowLitersPerMinute: 2.5 },
    { name: 'หมากเม่า (Mao Berry - ภูพาน)', plantSpacing: 4, rowSpacing: 4, waterNeed: 15, flowLitersPerMinute: 1.5 },
    { name: 'มะเกี่ยง (เชียงราย - คล้ายหว้า)', plantSpacing: 6, rowSpacing: 6, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'ตะขบป่า (หนามเยอะ)', plantSpacing: 5, rowSpacing: 5, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'มะเม่า (หลวง/สร้อย)', plantSpacing: 4, rowSpacing: 4, waterNeed: 20, flowLitersPerMinute: 1.5 },
    { name: 'มะหวด (ผลไม้ป่ารสฝาดหวาน)', plantSpacing: 5, rowSpacing: 5, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'ชำมะเลียง (พุ่มเตี้ย)', plantSpacing: 3, rowSpacing: 3, waterNeed: 15, flowLitersPerMinute: 1.5 },
    { name: 'พืช/ท้อ (พันธุ์โครงการหลวง)', plantSpacing: 6, rowSpacing: 6, waterNeed: 50, flowLitersPerMinute: 3 },
    { name: 'สายหยุด (ดอกหอมเช้า)', plantSpacing: 3, rowSpacing: 3, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'การเวก/กระดังงาจีน (เลื้อยเร็ว/ร่มเงา)', plantSpacing: 5, rowSpacing: 5, waterNeed: 40, flowLitersPerMinute: 2.75 },
    // หน้า 7
    { name: 'ชมนาด (ข้าวใหม่ - หอมใบเตย)', plantSpacing: 3, rowSpacing: 3, waterNeed: 15, flowLitersPerMinute: 1.5 },
    { name: 'หิรัญญิการ์ (ดอกใหญ่/ซุ้มยักษ์)', plantSpacing: 6, rowSpacing: 6, waterNeed: 40, flowLitersPerMinute: 2.75 },
    { name: 'เล็บมือนาง (ดอกแดง/ซุ้ม)', plantSpacing: 3, rowSpacing: 3, waterNeed: 20, flowLitersPerMinute: 1.5 },
    { name: 'พวงคราม (ดอกม่วง/ซุ้ม)', plantSpacing: 3, rowSpacing: 3, waterNeed: 20, flowLitersPerMinute: 1.5 },
    { name: 'พวงแสด (ดอกส้ม/เมืองหนาว)', plantSpacing: 3, rowSpacing: 3, waterNeed: 20, flowLitersPerMinute: 1.5 },
    { name: 'กระถินเทพา (โตเร็วมาก/ทำเฟอร์ฯ)', plantSpacing: 3, rowSpacing: 3, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'กระถินณรงค์', plantSpacing: 3, rowSpacing: 3, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'ยูคาลิปตัส (K7/H4 - ตัดขาย)', plantSpacing: 3, rowSpacing: 3, waterNeed: 15, flowLitersPerMinute: 1.5 },
    { name: 'ไผ่ซางหม่น (น่าน - ลำสวย)', plantSpacing: 4, rowSpacing: 4, waterNeed: 40, flowLitersPerMinute: 2.75 },
    { name: 'ไผ่เลี้ยงหวาน (หน่อ)', plantSpacing: 3, rowSpacing: 3, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'ไผ่สร้างไพร (ลำแกร่ง)', plantSpacing: 4, rowSpacing: 4, waterNeed: 40, flowLitersPerMinute: 2.75 },
    { name: 'ไผ่สีสุก (หนาม/งานสาน)', plantSpacing: 5, rowSpacing: 5, waterNeed: 65, flowLitersPerMinute: 4 },
    { name: 'เหลืองปรีดียาธร (Tabebuia)', plantSpacing: 4, rowSpacing: 4, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'ชมพูพันธุ์ทิพย์ (ซากุระเมืองไทย)', plantSpacing: 6, rowSpacing: 6, waterNeed: 40, flowLitersPerMinute: 2.75 },
    { name: 'อินทนิลน้ำ (ทนน้ำท่วม/ดอกม่วง)', plantSpacing: 6, rowSpacing: 6, waterNeed: 50, flowLitersPerMinute: 3 },
    { name: 'เสลา (เปลือกแตก/ดอกม่วง)', plantSpacing: 5, rowSpacing: 5, waterNeed: 40, flowLitersPerMinute: 2.75 },
    { name: 'ตะแบกนา (ลำต้นเกลี้ยง)', plantSpacing: 6, rowSpacing: 6, waterNeed: 40, flowLitersPerMinute: 3 },
    { name: 'สัตตบรรณ (ตีนเป็ด - ร่มเงา/เหม็น)', plantSpacing: 6, rowSpacing: 6, waterNeed: 40, flowLitersPerMinute: 3 },
    { name: 'หูกระจง (แผ่บารมี - รากแรง)', plantSpacing: 8, rowSpacing: 8, waterNeed: 65, flowLitersPerMinute: 3.5 },
    { name: 'แคนา (ป่า - ต้นใหญ่)', plantSpacing: 6, rowSpacing: 6, waterNeed: 50, flowLitersPerMinute: 3 },
    { name: 'มะฮอกกานีใบใหญ่ (ไม้ถนน)', plantSpacing: 6, rowSpacing: 6, waterNeed: 40, flowLitersPerMinute: 3 },
    { name: 'ประดู่กิ่งอ่อน (Angsana - ไม้ถนน)', plantSpacing: 8, rowSpacing: 8, waterNeed: 50, flowLitersPerMinute: 3 },
    { name: 'ปาล์มหางกระรอก (Foxtail)', plantSpacing: 3, rowSpacing: 3, waterNeed: 15, flowLitersPerMinute: 1.75 },
    { name: 'ปาล์มยะวา', plantSpacing: 3, rowSpacing: 3, waterNeed: 20, flowLitersPerMinute: 2 },
    { name: 'อินทผลัม (กินผลแห้ง - Medjool)', plantSpacing: 8, rowSpacing: 8, waterNeed: 175, flowLitersPerMinute: 5.5 },
    { name: 'ปาล์มพัดจีบ', plantSpacing: 3, rowSpacing: 3, waterNeed: 20, flowLitersPerMinute: 2 },
    { name: 'ตาลฟ้า (Bismarckia - ใบเงิน)', plantSpacing: 6, rowSpacing: 6, waterNeed: 40, flowLitersPerMinute: 2.75 },
    { name: 'มะม่วงน้ำดอกไม้เบอร์ 4 (ทวาย)', plantSpacing: 6, rowSpacing: 6, waterNeed: 70, flowLitersPerMinute: 3.5 },
    { name: 'มะม่วงพิมเสนมัน (กินดิบ/เปรี้ยว)', plantSpacing: 6, rowSpacing: 6, waterNeed: 70, flowLitersPerMinute: 3 },
    { name: 'มะม่วงแรด (กินดิบ/กรอบ)', plantSpacing: 6, rowSpacing: 6, waterNeed: 70, flowLitersPerMinute: 3 },
    { name: 'มะม่วงขายตึก (กรอบ/ลูกใหญ่)', plantSpacing: 6, rowSpacing: 6, waterNeed: 75, flowLitersPerMinute: 3 },
    { name: 'มะม่วงอกร่องพิกุลทอง', plantSpacing: 8, rowSpacing: 8, waterNeed: 90, flowLitersPerMinute: 4 },
    { name: 'ลิ้นจี่ฮงฮวย (พันธุ์เบา)', plantSpacing: 8, rowSpacing: 8, waterNeed: 125, flowLitersPerMinute: 4.5 },
    { name: 'ลิ้นจี่จักรพรรดิ์ (พันธุ์หนัก/ฝาง)', plantSpacing: 8, rowSpacing: 8, waterNeed: 150, flowLitersPerMinute: 5.5 },
    { name: 'ลำไยอีดอ (พันธุ์เบา/ยอดนิยม)', plantSpacing: 8, rowSpacing: 8, waterNeed: 115, flowLitersPerMinute: 4.5 },
    { name: 'ลำไยสีชมพู (เนื้อหนา/กลิ่นหอม)', plantSpacing: 8, rowSpacing: 8, waterNeed: 115, flowLitersPerMinute: 4.5 },
    { name: 'ชมพู่เพชรสายรุ้ง (เพชรบุรี - หวานจัด)', plantSpacing: 6, rowSpacing: 6, waterNeed: 110, flowLitersPerMinute: 4.5 },
    { name: 'น้อยหน่าฝ้าย (พันธุ์พื้นเมือง)', plantSpacing: 3, rowSpacing: 3, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'น้อยหน่าหนัง (พันธุ์เนื้อเหนียว)', plantSpacing: 3, rowSpacing: 3, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'น้อยหน่าเพชรปากช่อง (ลูกยักษ์)', plantSpacing: 4, rowSpacing: 4, waterNeed: 50, flowLitersPerMinute: 3 },
    { name: 'พุทราจัมโบ้ (ลูกเท่าแอปเปิ้ล)', plantSpacing: 5, rowSpacing: 5, waterNeed: 50, flowLitersPerMinute: 3 },
    { name: 'ส้มโอขาวน้ำผึ้ง (นครปฐม)', plantSpacing: 8, rowSpacing: 8, waterNeed: 100, flowLitersPerMinute: 4.5 },
    { name: 'โมกมัน (ไม้แกะสลัก/เนื้อขาว)', plantSpacing: 4, rowSpacing: 4, waterNeed: 15, flowLitersPerMinute: 2 },
    { name: 'รกฟ้า (Terminalia - ไม้ลายสวย)', plantSpacing: 5, rowSpacing: 5, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'มะค่าแต้ (เมล็ดดำ/ไม้แข็ง)', plantSpacing: 6, rowSpacing: 6, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'กระทิง (สารภีทะเล - ไม้ถนน)', plantSpacing: 6, rowSpacing: 6, waterNeed: 35, flowLitersPerMinute: 2.5 },
    { name: 'จิกทะเล (ชอบดินทราย/เค็ม)', plantSpacing: 5, rowSpacing: 5, waterNeed: 40, flowLitersPerMinute: 3 },
    { name: 'โพทะเล (Portia Tree)', plantSpacing: 6, rowSpacing: 6, waterNeed: 40, flowLitersPerMinute: 3 },
    { name: 'ฝาง (Sappan - สีย้อม/ยา)', plantSpacing: 3, rowSpacing: 3, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'ลำพู (ต้นหิ่งห้อย - ริมน้ำ)', plantSpacing: 6, rowSpacing: 6, waterNeed: 50, flowLitersPerMinute: 3 },
    { name: 'จาก (Nipa Palm - มุงหลังคา)', plantSpacing: 3, rowSpacing: 3, waterNeed: 40, flowLitersPerMinute: 3 },
    { name: 'หูกวาง (Sea Almond - ร่มเงา)', plantSpacing: 8, rowSpacing: 8, waterNeed: 50, flowLitersPerMinute: 3 },
    { name: 'สารภีทะเล (กันลมชายฝั่ง)', plantSpacing: 5, rowSpacing: 5, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'มะเกลือ (Ebony - ย้อมผ้า/ผล)', plantSpacing: 8, rowSpacing: 8, waterNeed: 40, flowLitersPerMinute: 3 },
    { name: 'ตะโกนา (ทำบอนไซ/ผลกินได้)', plantSpacing: 4, rowSpacing: 4, waterNeed: 20, flowLitersPerMinute: 1.5 },
    { name: 'ไผ่ซางนวล (ลำขาวสวย/จักสาน)', plantSpacing: 4, rowSpacing: 4, waterNeed: 40, flowLitersPerMinute: 2.75 },
    { name: 'ไผ่บงใหญ่ (หน่อหวาน/เฟอร์นิเจอร์)', plantSpacing: 4, rowSpacing: 4, waterNeed: 40, flowLitersPerMinute: 2.75 },
    { name: 'ไผ่ข้าวหลาม (กาบแดง/ทำข้าวหลาม)', plantSpacing: 3, rowSpacing: 3, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'ไผ่ดำอินโด (Black Bamboo)', plantSpacing: 3, rowSpacing: 3, waterNeed: 20, flowLitersPerMinute: 1.75 },
    // หน้า 8
    { name: 'ปาล์มหงส์เหิน', plantSpacing: 3, rowSpacing: 3, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'ปาล์มแว็กซ์ (Wax Palm)', plantSpacing: 3, rowSpacing: 3, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'บุหงาแต่งงาน (ช่อขาว)', plantSpacing: 3, rowSpacing: 3, waterNeed: 20, flowLitersPerMinute: 1.75 },
    { name: 'แก้วหิมาลัย (ใบฝอย/ดอกดก)', plantSpacing: 3, rowSpacing: 3, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'โมกราชินี (ใบหนา/ดอกใหญ่)', plantSpacing: 3, rowSpacing: 3, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'ชงโคฮอลแลนด์ (ดอกใหญ่/ใบมัน)', plantSpacing: 4, rowSpacing: 4, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'อรพิม (คิ้วนาง - เถาเนื้อแข็ง)', plantSpacing: 4, rowSpacing: 4, waterNeed: 20, flowLitersPerMinute: 1.5 },
    { name: 'พวงโกเมน (ดอกแดง/ซุ้ม)', plantSpacing: 4, rowSpacing: 4, waterNeed: 20, flowLitersPerMinute: 1.5 },
    { name: 'เตยทะเล (Pandan Laut - ริมทะเล)', plantSpacing: 3, rowSpacing: 3, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'ส้มแขก (Garcinia - ภาคใต้)', plantSpacing: 6, rowSpacing: 6, waterNeed: 40, flowLitersPerMinute: 3 },
    { name: 'อัลมอนด์ (Almond - California)', plantSpacing: 6, rowSpacing: 6, waterNeed: 50, flowLitersPerMinute: 3 },
    { name: 'วอลนัท (Walnut - Chandler)', plantSpacing: 8, rowSpacing: 8, waterNeed: 100, flowLitersPerMinute: 4.5 },
    { name: 'พีแคน (Pecan - USA)', plantSpacing: 10, rowSpacing: 10, waterNeed: 125, flowLitersPerMinute: 6 },
    { name: 'พิสตาชิโอ (Pistachio - Iran/USA)', plantSpacing: 6, rowSpacing: 6, waterNeed: 40, flowLitersPerMinute: 2.5 },
    { name: 'แมคคาเดเมีย (Macadamia - Hawaii/Au)', plantSpacing: 8, rowSpacing: 8, waterNeed: 50, flowLitersPerMinute: 3 },
    { name: 'เฮเซลนัท (Hazelnut - Europe)', plantSpacing: 5, rowSpacing: 5, waterNeed: 35, flowLitersPerMinute: 2.25 },
    { name: 'เกาลัด (Chestnut - จีน/ญี่ปุ่น)', plantSpacing: 8, rowSpacing: 8, waterNeed: 65, flowLitersPerMinute: 3.5 },
    { name: 'เม็ดมะม่วงหิมพานต์ (Vietnam Variety)', plantSpacing: 6, rowSpacing: 6, waterNeed: 40, flowLitersPerMinute: 2.75 },
    { name: 'ถั่วบราซิล (Brazil Nut - Amazon)', plantSpacing: 10, rowSpacing: 10, waterNeed: 100, flowLitersPerMinute: 5 },
    { name: 'ไพน์นัท (Pine Nut - สนกินเม็ด)', plantSpacing: 4, rowSpacing: 4, waterNeed: 15, flowLitersPerMinute: 1.5 },
    { name: 'แอปเปิ้ล (Fuji/Gala - ญี่ปุ่น/NZ)', plantSpacing: 4, rowSpacing: 4, waterNeed: 20, flowLitersPerMinute: 2 },
    { name: 'สาลี่หอม (Bartlett Pear)', plantSpacing: 4, rowSpacing: 4, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'เชอร์รี่ (Bing Cherry - USA)', plantSpacing: 5, rowSpacing: 5, waterNeed: 40, flowLitersPerMinute: 2.5 },
    { name: 'พืช/เนคทารีน (Donut Peach)', plantSpacing: 4, rowSpacing: 4, waterNeed: 30, flowLitersPerMinute: 2 },
    { name: 'แอปริคอต (Apricot - ตุรกี)', plantSpacing: 5, rowSpacing: 5, waterNeed: 35, flowLitersPerMinute: 2 },
    { name: 'พลัม/พรุน (European Plum)', plantSpacing: 5, rowSpacing: 5, waterNeed: 40, flowLitersPerMinute: 2.5 },
    { name: 'ควินซ์ (Quince - ผลไม้โบราณ)', plantSpacing: 4, rowSpacing: 4, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'พลับ (Fuyu - ญี่ปุ่น)', plantSpacing: 6, rowSpacing: 6, waterNeed: 50, flowLitersPerMinute: 3 },
    { name: 'กีวี่ (Hayward Green - NZ)', plantSpacing: 5, rowSpacing: 4, waterNeed: 40, flowLitersPerMinute: 2.5 },
    { name: 'กีวี่สีทอง (Gold Kiwi)', plantSpacing: 5, rowSpacing: 4, waterNeed: 40, flowLitersPerMinute: 2.5 },
    { name: 'เอลเดอร์เบอร์รี่ (Elderberry - ยา)', plantSpacing: 3, rowSpacing: 3, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'อาซาอิ (Acai Palm - Brazil)', plantSpacing: 3, rowSpacing: 3, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'มะกอกโอลีฟ (Olive - น้ำมัน)', plantSpacing: 6, rowSpacing: 6, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'มะกอกโอลีฟ (Table Olive - กินผล)', plantSpacing: 6, rowSpacing: 6, waterNeed: 35, flowLitersPerMinute: 2.5 },
    { name: 'องุ่นทานสด (Shine Muscat - ญี่ปุ่น)', plantSpacing: 6, rowSpacing: 3, waterNeed: 15, flowLitersPerMinute: 1.25 },
    { name: 'องุ่นเคียวโฮ (Kyoho)', plantSpacing: 6, rowSpacing: 3, waterNeed: 15, flowLitersPerMinute: 1.5 },
    { name: 'มะเดื่อฝรั่ง (Black Mission Fig)', plantSpacing: 3, rowSpacing: 3, waterNeed: 12, flowLitersPerMinute: 1.25 },
    { name: 'ทับทิม (Wonderful - USA)', plantSpacing: 4, rowSpacing: 4, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'อินทผลัม (Medjool - Israel/USA)', plantSpacing: 8, rowSpacing: 8, waterNeed: 175, flowLitersPerMinute: 5.5 },
    { name: 'คารอบ (Carob - แทนช็อคโกแลต)', plantSpacing: 6, rowSpacing: 6, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'อโวคาโด (Hass - ตลาดโลก)', plantSpacing: 6, rowSpacing: 6, waterNeed: 50, flowLitersPerMinute: 3 },
    { name: 'อโวคาโด (Reed - ลูกกลม)', plantSpacing: 6, rowSpacing: 6, waterNeed: 50, flowLitersPerMinute: 3 },
    { name: 'อโวคาโด (Booth 7)', plantSpacing: 6, rowSpacing: 6, waterNeed: 50, flowLitersPerMinute: 3 },
    { name: 'น้อยหน่าออสเตรเลีย (African Pride)', plantSpacing: 4, rowSpacing: 4, waterNeed: 40, flowLitersPerMinute: 2.5 },
    { name: 'เชอริมอยา (Cherimoya - Andes)', plantSpacing: 5, rowSpacing: 5, waterNeed: 40, flowLitersPerMinute: 2.5 },
    { name: 'ไวท์ซาโปเต้ (White Sapote)', plantSpacing: 6, rowSpacing: 6, waterNeed: 50, flowLitersPerMinute: 3 },
    { name: 'แบล็คซาโปเต้ (Black Sapote - ช็อคโกแลต)', plantSpacing: 6, rowSpacing: 6, waterNeed: 50, flowLitersPerMinute: 3 },
    { name: 'มาร์เมย์ซาโปเต้ (Mamey Sapote)', plantSpacing: 8, rowSpacing: 8, waterNeed: 65, flowLitersPerMinute: 3.5 },
    { name: 'เอบิว (Abiu - ผลเหลือง)', plantSpacing: 4, rowSpacing: 4, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'คานิสเทล (Canistel - ละมุดไข่)', plantSpacing: 4, rowSpacing: 4, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'โกโก้ (Criollo - พันธุ์หอม)', plantSpacing: 3, rowSpacing: 3, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'จันทน์เทศ (Grenada Nutmeg)', plantSpacing: 6, rowSpacing: 6, waterNeed: 40, flowLitersPerMinute: 3 },
    { name: 'ปาล์มน้ำมัน (พันธุ์ไนจีเรีย)', plantSpacing: 9, rowSpacing: 9, waterNeed: 200, flowLitersPerMinute: 6 },
    { name: 'อาร์แกน (Argan Tree - Morocco)', plantSpacing: 6, rowSpacing: 6, waterNeed: 15, flowLitersPerMinute: 1.5 },
    { name: 'เชียบัตเตอร์ (Shea Tree - Africa)', plantSpacing: 8, rowSpacing: 8, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'ตง (Tung Oil Tree - จีน)', plantSpacing: 5, rowSpacing: 5, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'ยางพารา (พันธุ์มาเลเซีย)', plantSpacing: 7, rowSpacing: 3, waterNeed: 65, flowLitersPerMinute: 3.5 },
    { name: 'กวรานา (Guarana - คาเฟอีนสูง)', plantSpacing: 3, rowSpacing: 3, waterNeed: 20, flowLitersPerMinute: 2 },
    { name: 'เยอร์บามาเต (Yerba Mate - ชา)', plantSpacing: 3, rowSpacing: 3, waterNeed: 20, flowLitersPerMinute: 2 },
    // หน้า 9
    { name: 'คอร์กโอ๊ค (Cork Oak - ทำจุกไวน์)', plantSpacing: 6, rowSpacing: 6, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'ยูคาลิปตัส (พันธุ์ออสเตรเลีย)', plantSpacing: 3, rowSpacing: 3, waterNeed: 20, flowLitersPerMinute: 1.5 },
    { name: 'ฟักทองยักษ์ (Atlantic Giant)', plantSpacing: 5, rowSpacing: 5, waterNeed: 75, flowLitersPerMinute: 4 },
    { name: 'เมเปิ้ล (Sugar Maple - Canada)', plantSpacing: 6, rowSpacing: 6, waterNeed: 40, flowLitersPerMinute: 3 },
    { name: 'เมเปิ้ลญี่ปุ่น (Momiji)', plantSpacing: 3, rowSpacing: 3, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'โอ๊ค (White Oak - ไม้ถังไวน์)', plantSpacing: 8, rowSpacing: 8, waterNeed: 40, flowLitersPerMinute: 3 },
    { name: 'ซากุระ (Cherry Blossom - ญี่ปุ่น)', plantSpacing: 6, rowSpacing: 6, waterNeed: 40, flowLitersPerMinute: 3 },
    { name: 'แปะก๊วย (Ginkgo Biloba)', plantSpacing: 6, rowSpacing: 6, waterNeed: 35, flowLitersPerMinute: 3 },
    { name: 'สนเรดวู้ด (California Redwood)', plantSpacing: 10, rowSpacing: 10, waterNeed: 100, flowLitersPerMinute: 5 },
    { name: 'สนซีดาร์ (Cedar)', plantSpacing: 6, rowSpacing: 6, waterNeed: 40, flowLitersPerMinute: 3 },
    { name: 'วิลโลว์ (Weeping Willow - ริมน้ำ)', plantSpacing: 6, rowSpacing: 6, waterNeed: 65, flowLitersPerMinute: 4 },
    { name: 'ป๊อปลาร์ (Poplar - ทำไม้)', plantSpacing: 3, rowSpacing: 3, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'พอพ่อ (Pawpaw - North America)', plantSpacing: 3, rowSpacing: 3, waterNeed: 20, flowLitersPerMinute: 1.75 },
    { name: 'เฟโจ้ว (Feijoa - Guavasteen)', plantSpacing: 3, rowSpacing: 3, waterNeed: 20, flowLitersPerMinute: 1.5 },
    { name: 'พีแคน (Pecan - Desirable variety)', plantSpacing: 10, rowSpacing: 10, waterNeed: 125, flowLitersPerMinute: 5.5 },
    { name: 'ลูคูมา (Lucuma - Eggfruit of Peru)', plantSpacing: 5, rowSpacing: 5, waterNeed: 40, flowLitersPerMinute: 2.5 },
    { name: 'จาโบติคาบา (Jabuticaba - องุ่นบราซิล)', plantSpacing: 4, rowSpacing: 4, waterNeed: 40, flowLitersPerMinute: 2.5 },
    { name: 'กราวิโอลา (Soursop - ทุเรียนเทศยักษ์)', plantSpacing: 5, rowSpacing: 5, waterNeed: 40, flowLitersPerMinute: 2.5 },
    { name: 'มารูลา (Marula - Africa/Amarula)', plantSpacing: 8, rowSpacing: 8, waterNeed: 50, flowLitersPerMinute: 3 },
    { name: 'เคปเปล (Keppel - อินโดนีเซีย/ไม้หอม)', plantSpacing: 6, rowSpacing: 6, waterNeed: 50, flowLitersPerMinute: 3 },
    { name: 'ยูซุ (Yuzu - ญี่ปุ่น)', plantSpacing: 4, rowSpacing: 4, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'คารา คารา (Cara Cara Navel - เนื้อแดง)', plantSpacing: 5, rowSpacing: 5, waterNeed: 40, flowLitersPerMinute: 2.5 },
    { name: 'บลัดออเรนจ์ (Blood Orange - อิตาลี)', plantSpacing: 5, rowSpacing: 5, waterNeed: 40, flowLitersPerMinute: 2.5 },
    { name: 'เกรปฟรุต (Ruby Red Grapefruit)', plantSpacing: 6, rowSpacing: 6, waterNeed: 65, flowLitersPerMinute: 3 },
    { name: 'ส้มแมนดาริน (Satsuma - ญี่ปุ่น)', plantSpacing: 4, rowSpacing: 4, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'มะกรูดอิตาลี (Bergamot - Earl Grey)', plantSpacing: 4, rowSpacing: 4, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'คาลาแมนซี (Calamansi - ฟิลิปปินส์)', plantSpacing: 3, rowSpacing: 3, waterNeed: 20, flowLitersPerMinute: 1.5 },
    { name: 'ซูทาชิ (Sudachi - ส้มเปรี้ยวญี่ปุ่น)', plantSpacing: 3, rowSpacing: 3, waterNeed: 20, flowLitersPerMinute: 1.5 },
    { name: 'โป๊ยกั๊ก (Star Anise - จีน/เวียดนาม)', plantSpacing: 5, rowSpacing: 5, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'ออลสไปซ์ (Allspice - Jamaica)', plantSpacing: 6, rowSpacing: 6, waterNeed: 35, flowLitersPerMinute: 2.5 },
    { name: 'อบเชยจีน (Cassia Cinnamon)', plantSpacing: 3, rowSpacing: 3, waterNeed: 20, flowLitersPerMinute: 1.5 },
    { name: 'พริกไทยเสฉวน (Sichuan Pepper)', plantSpacing: 3, rowSpacing: 3, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'ยูคาลิปตัสสีรุ้ง (Rainbow Eucalyptus)', plantSpacing: 5, rowSpacing: 5, waterNeed: 40, flowLitersPerMinute: 3 },
    { name: 'เบาบับ (Baobab - Africa)', plantSpacing: 10, rowSpacing: 10, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'เลือดมังกร (Dragon Blood Tree)', plantSpacing: 5, rowSpacing: 5, waterNeed: 12, flowLitersPerMinute: 1.5 },
    { name: 'เมเปิ้ลแดง (Red Maple)', plantSpacing: 5, rowSpacing: 5, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'สนบลู (Blue Spruce)', plantSpacing: 4, rowSpacing: 4, waterNeed: 20, flowLitersPerMinute: 2 },
    { name: 'ต้นเบิร์ช (Silver Birch)', plantSpacing: 4, rowSpacing: 4, waterNeed: 25, flowLitersPerMinute: 2 },
    { name: 'ต้นแอช (Ash Tree)', plantSpacing: 6, rowSpacing: 6, waterNeed: 40, flowLitersPerMinute: 3 },
    { name: 'ต้นเอล์ม (Elm Tree)', plantSpacing: 8, rowSpacing: 8, waterNeed: 50, flowLitersPerMinute: 3 },
    { name: 'จาคารันดา (Jacaranda - ศรีตรังออสฯ)', plantSpacing: 6, rowSpacing: 6, waterNeed: 40, flowLitersPerMinute: 3 },
    { name: 'แมกโนเลีย (Magnolia Grandiflora)', plantSpacing: 5, rowSpacing: 5, waterNeed: 30, flowLitersPerMinute: 2.5 },
    { name: 'ลอเรล (Bay Laurel - ใบกระวาน)', plantSpacing: 3, rowSpacing: 3, waterNeed: 12, flowLitersPerMinute: 1.5 }
];

export default horticultureData;